#%RAML 1.0 NamedExample
value: |
    {
      "shoppingCartId": "cart-0000123456",
      "customerId": "cust-000012345",
      "items": [
        {
          "productId": "prod-12345",
          "variantId": "var123456789",
          "quantity": 2,
          "tax": 5.25,
          "shipping": 5.00
        },
        {
          "productId": "prod-54321",
          "variantId": "var987654321",
          "quantity": 1,
          "tax": 6.25,
          "shipping": 10.00
        }
      ],
      "created": "2020-12-24T09:43:25.218Z"
    }