#%RAML 1.0 NamedExample
value: |
          {
            "items": [
              {
                "productId": "prod-123456789",
                "variantId": "var123456789",
                "quantity": 2
              },
              {
                "productId": "prod-0987654321",
                "variantId": "var987654321",
                "quantity": 1
              }
            ]
          }
        